[package]
name = "simple-wc3"
version = "0.0.6"
edition = "2024"

[dependencies]
iroh = "0.96.0"
tokio = { version = "1.49.0", features = ["net", "macros"] }
binrw = "0.15.0"

[profile.release]
lto = true
strip = true
opt-level = "s"   # Optimize for size.
codegen-units = 1
panic = "abort"
