[package]
name = "simple-wc3"
version = "0.0.4"
edition = "2024"

[dependencies]
iroh = "0.95.1"
tokio = { version = "1.49.0", features = ["net", "macros"] }
binrw = "0.15.0"

[profile.release]
lto = true
strip = true
opt-level = "z" # Optimize for size.
